package govern

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/anthropic/claude-go/pkg/agent"
)

// writeSkill 造一份 SKILL.md。
func writeSkill(t *testing.T, frontmatter string) string {
	t.Helper()
	dir := filepath.Join(t.TempDir(), "some-skill")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	p := filepath.Join(dir, "SKILL.md")
	body := "---\n" + frontmatter + "\n---\n\n技能正文。\n"
	if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	return p
}

// --- 核心安全属性: 自动产物不得给自己发写/执行权限 ---

func TestCheckNoEscalation_自动产物声明Bash被拒(t *testing.T) {
	v := CheckNoEscalation(Product{
		Name: "auto-x", Kind: "skill", AutoGenerated: true,
		DeclaredTools: []string{"Read", "Bash"},
	}, nil)
	if v.Allowed {
		t.Fatal("自动提炼的技能声明 Bash 必须被拒 —— 否则被优化的系统能自己扩大动作空间")
	}
	joined := strings.Join(v.Reasons, " ")
	if !strings.Contains(joined, "Bash") {
		t.Errorf("拒绝理由要点名越界的工具, got %v", v.Reasons)
	}
	if v.Effective != nil {
		t.Error("拒绝时不该返回合成约束 (免得调用方误用)")
	}
	if v.Error() == nil {
		t.Error("Verdict.Error() 在拒绝时必须返回非 nil")
	}
}

func TestCheckNoEscalation_自动产物只读声明放行(t *testing.T) {
	v := CheckNoEscalation(Product{
		Name: "auto-y", Kind: "skill", AutoGenerated: true,
		DeclaredTools: []string{"Read", "Grep", "WebFetch"},
	}, nil)
	if !v.Allowed {
		t.Fatalf("只读工具声明应放行, got %v", v.Reasons)
	}
	if v.Effective == nil {
		t.Error("放行时应给出合成后的有效约束, 供调用方留痕")
	}
}

// 什么都不声明的产物继承宿主档位, 不构成提权。
func TestCheckNoEscalation_未声明工具放行(t *testing.T) {
	if v := CheckNoEscalation(Product{Name: "plain", AutoGenerated: true}, nil); !v.Allowed {
		t.Fatalf("未声明任何工具不构成提权, 应放行: %v", v.Reasons)
	}
}

// fail-closed: 不认识的工具名一律拒绝 (可能是打错了, 也可能是没建模的提权面)。
func TestCheckNoEscalation_未知工具名被拒(t *testing.T) {
	v := CheckNoEscalation(Product{
		Name: "weird", DeclaredTools: []string{"SudoRunEverything"},
	}, nil)
	if v.Allowed {
		t.Fatal("不认识的工具名必须拒绝 (fail-closed)")
	}
	if !strings.Contains(strings.Join(v.Reasons, " "), "不认识") {
		t.Errorf("理由应说明是不认识, got %v", v.Reasons)
	}
}

// 权限档放宽 (bypass 比 default 松) 必须被拒 —— 复用 ConstraintSet 的严格度阶梯。
func TestCheckNoEscalation_权限档放宽被拒(t *testing.T) {
	v := CheckNoEscalation(Product{Name: "p", Permission: "bypass"}, HumanBaseline())
	if v.Allowed {
		t.Fatal("声明 bypassPermissions 比基线 default 更松, 必须拒绝")
	}
	if !strings.Contains(strings.Join(v.Reasons, " "), "更松") {
		t.Errorf("理由应复用 ConstraintSet 的措辞, got %v", v.Reasons)
	}
}

// 收紧权限档 (plan 比 default 紧) 应放行。
func TestCheckNoEscalation_权限档收紧放行(t *testing.T) {
	if v := CheckNoEscalation(Product{Name: "p", Permission: "plan"}, HumanBaseline()); !v.Allowed {
		t.Fatalf("plan 比 default 更紧, 应放行: %v", v.Reasons)
	}
}

// 无名产物拒绝: 留不了痕就不能过闸 (必留痕是四律之一)。
func TestCheckNoEscalation_无名产物被拒(t *testing.T) {
	if v := CheckNoEscalation(Product{Name: "  "}, nil); v.Allowed {
		t.Fatal("无名产物必须拒绝")
	}
}

// 人工产物基线更宽: 人写的技能声明 Bash 是正常的。
func TestCheckNoEscalation_人工产物可声明Bash(t *testing.T) {
	v := CheckNoEscalation(Product{
		Name: "human-skill", AutoGenerated: false, DeclaredTools: []string{"Read", "Bash"},
	}, nil)
	if !v.Allowed {
		t.Fatalf("人写的技能声明 Bash 应放行 (仓内既有技能就有), got %v", v.Reasons)
	}
}

// 显式基线优先于默认基线: 运维放宽是一个明确的人为动作。
func TestCheckNoEscalation_显式基线可放宽自动产物(t *testing.T) {
	wide := agent.NewConstraintSet("test:wide").WithToolAllowList([]string{"Read", "Bash"})
	v := CheckNoEscalation(Product{
		Name: "auto-z", AutoGenerated: true, DeclaredTools: []string{"Bash"},
	}, wide)
	// 白名单过了, 但自动产物的 mutating 硬闸仍然挡住 —— 两道一起, 单点放宽不等于提权。
	if v.Allowed {
		t.Fatal("即便基线放宽白名单, 自动产物的写/执行硬闸仍应拦住 Bash")
	}
	if !strings.Contains(strings.Join(v.Reasons, " "), "自动提炼产物不得声明写/执行类工具") {
		t.Errorf("应由 mutating 硬闸拦下, got %v", v.Reasons)
	}
}

// --- CheckSkillPromotion 端到端 ---

func TestCheckSkillPromotion_解析失败必拒(t *testing.T) {
	v := CheckSkillPromotion(filepath.Join(t.TempDir(), "不存在", "SKILL.md"), nil)
	if v.Allowed {
		t.Fatal("读不到 SKILL.md 必须拒绝 —— 绝不能'当作没声明'")
	}
	if !strings.Contains(strings.Join(v.Reasons, " "), "解析失败") {
		t.Errorf("理由应说明解析失败, got %v", v.Reasons)
	}
}

func TestCheckSkillPromotion_自动技能声明Bash被拒(t *testing.T) {
	p := writeSkill(t, "name: auto-bad\ndescription: 自动提炼\nauto_generated: true\nstatus: shadow\nallowed-tools: Read, Bash")
	v := CheckSkillPromotion(p, nil)
	if v.Allowed {
		t.Fatalf("auto_generated 技能声明 Bash 必须拒绝")
	}
}

func TestCheckSkillPromotion_自动技能只读放行(t *testing.T) {
	p := writeSkill(t, "name: auto-ok\ndescription: 自动提炼\nauto_generated: true\nstatus: shadow\nallowed-tools: Read, Grep")
	if v := CheckSkillPromotion(p, nil); !v.Allowed {
		t.Fatalf("只读声明应放行: %v", v.Reasons)
	}
}

// 缺 auto_generated 标记时按"自动产物"处理 (更严那一侧)。
func TestIsAutoGenerated_读不到时按自动处理(t *testing.T) {
	if !isAutoGenerated(filepath.Join(t.TempDir(), "nope.md")) {
		t.Error("读不到文件时应按自动产物处理 (fail-closed)")
	}
	p := writeSkill(t, "name: x\ndescription: 人写的")
	if isAutoGenerated(p) {
		t.Error("无 auto_generated 行的技能不该被判为自动产物")
	}
}

// 基线本身必须是合法约束, 否则 Narrow 会在"父约束不合法"上失败。
func TestDefaultBaseline_自身合法且为只读档(t *testing.T) {
	b := DefaultBaseline()
	if err := b.Validate(); err != nil {
		t.Fatalf("默认基线自身应合法: %v", err)
	}
	if b.ToolProfile() != agent.ProfileAnalysis {
		t.Errorf("默认基线应为 analysis 只读档, got %q", b.ToolProfile())
	}
	if b.Tools == nil || b.Tools.Allow == nil {
		t.Fatal("Allow 必须非 nil 才构成白名单 (nil 是'不设名单', 那就不挡任何东西)")
	}
}
