// Package govern 治理四律里此前完全缺席的那一条: **不越权** (design/03 §4.6)。
//
// # 四律的现状与本包的位置
//
//	必留痕  谱系: SKILL.md 的 audit 行 + learners.Proposal.Parent —— 已有。
//	可回滚  evo rollback / SetStatus —— 已有。
//	必过闸  Skill.Status 运行期排除 shadow + 回放 harness —— 已有。
//	不越权  ConstraintSet 单调性 —— **本包**。
//
// # 为什么必须是 fail-closed
//
// 其余三律错了会丢学习效果; 这一律错了会**放权**。一个 LLM 自己写出来的 SKILL.md
// 若能在 frontmatter 里声明 `allowed-tools: [Bash]` 并被晋升成 active, 那就是让
// "被优化的系统"自己扩大自己的动作空间 —— 设计 §4.7 那句"闸门标准本身不在它的动作
// 空间里"讲的就是这个。所以本包的每条判据都取拒绝侧的默认值:
//
//   - 解析不了 SKILL.md → 拒绝 (不是"当作没声明")。
//   - 声明了本仓不认识的工具名 → 拒绝 (不认识就不放行)。
//   - 声明的约束不能被证明是基线的收窄 → 拒绝 (Narrow 返回 error 即拒绝)。
//   - 自动提炼的产物额外要求: 不得声明任何写/执行类工具, 哪怕基线允许。
//
// # 不另造机制
//
// 单调性判定**直接复用** pkg/agent.ConstraintSet.Narrow —— 那是仓内既有的、带测试的
// "约束只能收窄不能放宽"实现 (design/01 §4.6)。本包只做两件它没做的事: 从 SKILL.md /
// 草案里**解析出** ConstraintSet, 以及给自动产物定一条更严的基线。
package govern

import (
	"fmt"
	"sort"
	"strings"

	"github.com/anthropic/claude-go/pkg/agent"
	"github.com/anthropic/claude-go/pkg/skills"
)

// baselineReadOnlyTools 自动提炼产物的默认工具上界。
//
// 取值 = pkg/tool/builtin 的 analysis 档位那批只读工具 (定位 + 读取 + 联网调研)。
// 锁定为不可导出常量数组: 这是 H7 的"锁定字段", agent 请求放宽应当被拒绝而不是被满足。
//
// 为什么连 WebFetch/WebSearch 都算只读: 它们不改本机状态。真正要挡的是 Bash /
// Write / Edit / 建索引 / Cron 这类能落地副作用的。
var baselineReadOnlyTools = []string{
	"Read", "FileRead", "Glob", "Grep",
	"WebFetch", "WebSearch",
	"CodeIntelQuery", "CodeIntelStatus",
	"StructuredOutput", "ToolSearch", "Skill",
}

// mutatingTools 明确的写/执行类工具名 (含常见别名)。
//
// 这张表是**黑名单侧的兜底**: 白名单已经能挡住绝大多数情形, 但白名单只在产物声明了
// allow 列表时才生效; 若某天基线被运维放宽, 这张表仍然挡住自动产物拿写权限。
// 两道一起 = 单点放宽不会直接变成提权。
var mutatingTools = map[string]bool{
	"bash": true, "shell": true, "filewrite": true, "write": true,
	"fileedit": true, "edit": true, "strreplace": true, "multiedit": true,
	"notebookedit": true, "codeintelinit": true, "codeintelupdate": true,
	"croncreate": true, "crondelete": true, "enterworktree": true,
	"teamcreate": true, "teamdelete": true, "computeruse": true,
	"generatevideo": true, "generateimage": true, "generategif": true,
	"generatepptx": true, "generatespeech": true, "generatechart": true,
}

// knownTools 本仓认识的工具名集合 (小写)。用于"不认识就不放行"。
//
// 由 baselineReadOnlyTools + mutatingTools + 少量既有工具名合成。刻意不去动态读
// tool.Registry: 治理判定不该依赖"此刻这个进程注册了什么" —— 同一份 SKILL.md 在
// 装了不同工具档位的两个宿主上必须得到同一个治理结论。
var knownTools = func() map[string]bool {
	m := map[string]bool{}
	for _, t := range baselineReadOnlyTools {
		m[strings.ToLower(t)] = true
	}
	for t := range mutatingTools {
		m[t] = true
	}
	for _, t := range []string{
		"todowrite", "taskcreate", "taskget", "taskupdate", "tasklist",
		"askuserquestion", "enterplanmode", "exitplanmode", "sendmessage",
		"taskoutput", "taskstop", "lsp", "config", "codeintelbranch",
		"exitworktree", "cronlist", "kline", "quote",
	} {
		m[t] = true
	}
	return m
}()

// Verdict 一次不越权检查的结论。
type Verdict struct {
	Allowed bool     `json:"allowed"`
	Product string   `json:"product"`
	Reasons []string `json:"reasons,omitempty"` // Allowed=false 时的拒绝理由 (逐条)
	// Effective 通过时的合成约束 (基线 ∩ 产物声明), 供调用方落痕。
	Effective *agent.ConstraintSet `json:"effective,omitempty"`
}

// Error 把拒绝转成 error, 方便调用方直接 `if err := v.Error(); err != nil`。
func (v Verdict) Error() error {
	if v.Allowed {
		return nil
	}
	return fmt.Errorf("不越权检查拒绝 %s: %s", v.Product, strings.Join(v.Reasons, "; "))
}

// DefaultBaseline 自动提炼产物的基线约束。
//
// 三处取值都是刻意的:
//   - Tools.Profile = analysis: 只读分析档, 是六个档位里最窄的一个有意义档位。
//   - Tools.Allow = 只读集 (非 nil!): 非 nil 才构成白名单, 产物声明的每个工具都得在里面。
//   - Permission 留空: 空 = default 档 (每次询问)。产物若声明 bypass/acceptEdits,
//     permissionStrictness 会判它比 default 更松从而拒绝 —— 这正是要的。
//     若这里写成 plan (最紧), 则任何**未声明**权限档的产物都会因"default 比 plan 松"
//     被拒, 一个都过不去, 治理就从 fail-closed 退化成 fail-shut。
func DefaultBaseline() *agent.ConstraintSet {
	return agent.NewConstraintSet("govern:auto-product-baseline").
		WithToolProfile(agent.ProfileAnalysis).
		WithToolAllowList(baselineReadOnlyTools)
}

// HumanBaseline 人工技能/产物的基线。
//
// 比 DefaultBaseline 宽: 人写的技能声明 Bash 是正常的 (仓内既有技能就有)。这里只做
// 两件事 —— 认不出的工具名拒绝、权限档不得放宽。工具白名单不设 (Allow 保持 nil)。
func HumanBaseline() *agent.ConstraintSet {
	return agent.NewConstraintSet("govern:human-product-baseline")
}

// Product 待检查的进化产物的声明面。
type Product struct {
	Name string
	Kind string // skill | prompt | workflow
	// AutoGenerated 是否为自动提炼产物 (决定用哪条基线)。
	AutoGenerated bool
	// DeclaredTools frontmatter 里声明的工具名 (原文, 未归一)。
	DeclaredTools []string
	// Permission 声明的权限档 (通常为空)。
	Permission string
	// Origin 审计标记。
	Origin string
}

// CheckNoEscalation 不越权检查 (design/03 §4.6 四律之"不越权")。
//
// baseline 为 nil 时按 product.AutoGenerated 选默认基线 —— 注意这**不是**"没有基线
// 就放行", 而是"没有基线就用最严的那条"。
func CheckNoEscalation(p Product, baseline *agent.ConstraintSet) Verdict {
	v := Verdict{Product: p.Name}
	if strings.TrimSpace(p.Name) == "" {
		v.Reasons = append(v.Reasons, "产物无名: 无法留痕, 拒绝")
		return v
	}
	if baseline == nil {
		if p.AutoGenerated {
			baseline = DefaultBaseline()
		} else {
			baseline = HumanBaseline()
		}
	}

	// ① 工具名必须都认识。不认识的名字有两种可能: 打错了, 或者是某个我们没建模的
	// 提权面 —— 两种都不该放行。
	var unknown []string
	for _, t := range p.DeclaredTools {
		n := strings.ToLower(strings.TrimSpace(t))
		if n == "" {
			continue
		}
		if !knownTools[n] {
			unknown = append(unknown, t)
		}
	}
	if len(unknown) > 0 {
		sort.Strings(unknown)
		v.Reasons = append(v.Reasons, "声明了本仓不认识的工具: "+strings.Join(unknown, ","))
	}

	// ② 自动产物的额外硬闸: 一个写/执行类工具都不许声明。
	// 这一条在白名单之外单独存在, 见 mutatingTools 的注释。
	if p.AutoGenerated {
		var mut []string
		for _, t := range p.DeclaredTools {
			if mutatingTools[strings.ToLower(strings.TrimSpace(t))] {
				mut = append(mut, t)
			}
		}
		if len(mut) > 0 {
			sort.Strings(mut)
			v.Reasons = append(v.Reasons, "自动提炼产物不得声明写/执行类工具: "+strings.Join(mut, ",")+
				" (LLM 写出来的东西不该自己给自己发写权限)")
		}
	}

	// ③ 单调性: 复用 ConstraintSet.Narrow。error 即拒绝, 绝不"退而用 child"。
	child := agent.NewConstraintSet(firstNonEmpty(p.Origin, "product:"+p.Name))
	if len(p.DeclaredTools) > 0 {
		child = child.WithToolAllowList(p.DeclaredTools)
	}
	if strings.TrimSpace(p.Permission) != "" {
		child = child.WithPermission(p.Permission)
	}
	eff, err := baseline.Narrow(child)
	if err != nil {
		v.Reasons = append(v.Reasons, "约束不是基线的收窄: "+err.Error())
	} else {
		v.Effective = eff
	}

	v.Allowed = len(v.Reasons) == 0
	if !v.Allowed {
		v.Effective = nil // 拒绝时不给合成结果, 免得调用方误用
	}
	return v
}

// CheckSkillPromotion 技能晋升前的不越权检查 (skillaudit / evo_promote 的前置闸)。
//
// 解析失败 → 拒绝。这一点值得强调: 最容易写错的是 `if err != nil { /* 当作没声明 */ }`,
// 那等于"坏掉的 frontmatter 自动获得放行"。
func CheckSkillPromotion(skillPath string, baseline *agent.ConstraintSet) Verdict {
	sk, err := skills.ParseSkillFile(skillPath, "managed")
	if err != nil || sk == nil {
		return Verdict{
			Product: skillPath,
			Reasons: []string{fmt.Sprintf("SKILL.md 解析失败, 无法判定权限面, 拒绝晋升: %v", err)},
		}
	}
	p := Product{
		Name:          firstNonEmpty(sk.Name, skillPath),
		Kind:          "skill",
		AutoGenerated: isAutoGenerated(skillPath),
		DeclaredTools: sk.AllowedTools,
		Origin:        "skill:" + sk.Name,
	}
	return CheckNoEscalation(p, baseline)
}

// isAutoGenerated 读 frontmatter 的 auto_generated 标记。
//
// pkg/skills.Skill 没有这个字段 (它只解析运行期需要的字段), 而进化门禁必须区分
// "人写的"与"LLM 写的" —— 两者基线不同。这里直接读文件而不去改 pkg/skills 的结构:
// 那是运行期热路径的类型, 为治理需求往里加字段不划算。
func isAutoGenerated(skillPath string) bool {
	data, err := readHead(skillPath, 1200)
	if err != nil {
		// 读不到就按"自动产物"处理 —— 更严的那一侧 (fail-closed)。
		return true
	}
	for _, ln := range strings.Split(data, "\n") {
		ln = strings.TrimSpace(ln)
		if strings.HasPrefix(ln, "auto_generated:") {
			val := strings.ToLower(strings.TrimSpace(strings.TrimPrefix(ln, "auto_generated:")))
			return val == "true" || val == "yes" || val == "1"
		}
		if ln == "---" && strings.Contains(data, "auto_generated") {
			continue
		}
	}
	return false
}

func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		if strings.TrimSpace(v) != "" {
			return v
		}
	}
	return ""
}
